version: 2

references:
  front_container_config: &front_container_config
    docker:
      - image: circleci/node-browsers
    working_directory: /home/circleci/project

  node_modules_cache_params: &node_modules_cache_params
    key: node_modules-{{ .Branch }}-{{ checksum "./client/package-lock.json" }}
    paths:
      - node_modules

  server_container_config: &server_container_config
    docker:
      - image: mercari/appengine-go
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /go/src/github.com/howdy39/study-gae-go-circle-ci

  go_vendoring_cache_params: &go_vendoring_cache_params
    key: go-vendoring-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
    paths:
      - /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor

jobs:
  front_build:
    <<: *front_container_config
    steps:
      - checkout
      - run:
          name: Show system information.
          command: |
            echo "Node $(node -v)"
            echo "Npm $(npm -v)"
      - restore_cache:
          name: Restore Cache.
          <<: *node_modules_cache_params
      - run:
          name: Set up to Angular.
          command: npm install --no-save
          working_directory: ./client
      - save_cache:
          name: Saving Cache.
          <<: *node_modules_cache_params
      - run:
          name: Run Angular Build.
          command: npm run build
          working_directory: ./client
      - run:
          name: Move dist directory.
          command: |
            mkdir -p attach_workspace
            cp -rp client/dist attach_workspace/dist
      - persist_to_workspace:
          root: attach_workspace
          paths:
            - dist
      - run: ls -la attach_workspace


  server_build:
    <<: *server_container_config
    steps:
      - checkout
      - run:
          name: Show system information.
          command: |
            echo "Go $(go version)"
      - restore_cache:
          name: Restore Cache.
          <<: *go_vendoring_cache_params
      - run:
          name: Vendoring.
          command: |
            if [ ! -e /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor ]; then
                go get -u github.com/golang/dep/cmd/dep
                dep ensure -v
            fi
      - save_cache:
          name: Saving Cache.
          <<: *go_vendoring_cache_params
      - run:
          name: Run Server Unit Tests.
          command: make test

  deploy:
    <<: *server_container_config
    steps:
      - checkout
      - attach_workspace:
          at: attach_workspace
      - run: ls -la attach_workspace/dist
      - run: cp -rp attach_workspace/dist api/src/templates
      - run: ls -la api/src/templates
      - run:
          name: Deploy to GAE.
          command: |
            if [ ${CIRCLE_BRANCH} = "demo" ]; then
              ./scripts/deploy-ci.sh
            else
              echo "${CIRCLE_BRANCH} isn't deploy branch."
            fi

workflows:
  version: 2
  build:
    jobs:
      - front_build
      - server_build
      - deploy:
          requires:
            - front_build
            - server_build
