version: 2

references:
  container_config: &container_config
    docker:
      - image: mercari/appengine-go
    environment:
     TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /go/src/github.com/howdy39/study-gae-go-circle-ci

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Vendoring.
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure -v
      - run:
          name: Run Server Unit Tests.
          command: make test
      - run:
          name: Deploy to GAE.
          command: |
            if [ ${CIRCLE_BRANCH} = "demo" ]; then
              ./scripts/deploy-ci.sh
            else
              echo "${CIRCLE_BRANCH} isn't deploy branch."
            fi
