version: 2

references:
  container_config: &container_config
    docker:
      - image: mercari/appengine-go
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /go/src/github.com/howdy39/study-gae-go-circle-ci

  go_vendoring_cache_params: &go_vendoring_cache_params
    key: go-vendoring-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
    paths:
      - /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache - vendor
          <<: *go_vendoring_cache_params
      - run:
          name: Vendoring.
          command: |
            if [ ! -e /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor ]; then
                go get -u github.com/golang/dep/cmd/dep
                dep ensure -v
            fi
      - save_cache:
          name: Saving Cache - vendor
          <<: *go_vendoring_cache_params
      - run:
          name: Run Server Unit Tests.
          command: make test
      - run:
          name: Deploy to GAE.
          command: |
            if [ ${CIRCLE_BRANCH} = "demo" ]; then
              ./scripts/deploy-ci.sh
            else
              echo "${CIRCLE_BRANCH} isn't deploy branch."
            fi
