version: 2

references:
  front_container_config: &front_container_config
    docker:
      - image: circleci/node
    working_directory: /home/circleci/project

  node_modules_cache_params: &node_modules_cache_params
    key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

  container_config: &container_config
    docker:
      - image: mercari/appengine-go
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /go/src/github.com/howdy39/study-gae-go-circle-ci

  go_vendoring_cache_params: &go_vendoring_cache_params
    key: go-vendoring-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
    paths:
      - /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor

jobs:
  build:
    <<: *front_container_config
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Npm $(npm -v)"
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output
      - run: cat my_workspace/echo-output

#      - restore_cache:
#          name: Restore Cache - node_modules
#          <<: *node_modules_cache_params
#          working_directory: ./client
#      - run:
#          name: Set up to Angular.
#          command: npm install --no-save
#          working_directory: ./client
#      - save_cache:
#          name: Saving Cache - node_modules
#          <<: *node_modules_cache_params
#          working_directory: ./client
#      - run:
#          name: Run Angular Lint.
#          command: npm run lint
#          working_directory: ./client
#      - run:
#          name: Run Angular Test.
#          command: npm run test
#          working_directory: ./client
#      - run:
#          name: Run Angular Buil.
#          command: npm run build
#          working_directory: ./client

  buildx:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache - vendor
          <<: *go_vendoring_cache_params
      - run:
          name: Vendoring.
          command: |
            if [ ! -e /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor ]; then
                go get -u github.com/golang/dep/cmd/dep
                dep ensure -v
            fi
      - save_cache:
          name: Saving Cache - vendor
          <<: *go_vendoring_cache_params
      - run:
          name: Run Server Unit Tests.
          command: make test
      - run:
          name: Deploy to GAE.
          command: |
            if [ ${CIRCLE_BRANCH} = "demo" ]; then
              ./scripts/deploy-ci.sh
            else
              echo "${CIRCLE_BRANCH} isn't deploy branch."
            fi
