version: 2
jobs:
 build:
  docker:
   - image: mercari/appengine-go
  environment:
   TZ: /usr/share/zoneinfo/Asia/Tokyo
  working_directory: /home/circleci/go/src/project
  steps:
   - checkout
   - run:
      name: Run Server Unit Tests.
      command: make test
   - run:
      name: Deploy to GAE.
      command: ./scripts/deploy-ci.sh
