version: 2

references:
  front_container_config: &front_container_config
    docker:
      - image: circleci/node
    working_directory: /home/circleci/project

  node_modules_cache_params: &node_modules_cache_params
    key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

  container_config: &container_config
    docker:
      - image: mercari/appengine-go
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /go/src/github.com/howdy39/study-gae-go-circle-ci

  go_vendoring_cache_params: &go_vendoring_cache_params
    key: go-vendoring-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
    paths:
      - /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor

jobs:
  build:
    <<: *front_container_config
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Npm $(npm -v)"
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
      - run: cat my_workspace/echo-output

  build_server:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - build
      - build_server:
          requires:
            - build