version: 2
jobs:
 build:
  docker:
   - image: mercari/appengine-go
  environment:
   TZ: /usr/share/zoneinfo/Asia/Tokyo
  working_directory: /home/circleci/go/src/project
  steps:
   - checkout
#   - run:
#      name: Set PATH to .bashrc.
#      command: |
#       echo 'export PATH=$HOME/go/bin:$HOME/go_appengine:$PATH' >> $BASH_ENV
#       source /home/circleci/.bashrc
#   - run:
#      name: Make GOPATH directory.
#      command: mkdir -p $HOME/go/src
#   - run:
#      name: Set GOPATH to .bashrc.
#      command: |
#       echo 'export GOPATH=$HOME/go' >> $BASH_ENV
#       source /home/circleci/.bashrc
#   - run:
#      name: Install appengine sdk.
#      command: |
#       wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.58.zip
#       unzip go_appengine_sdk_linux_amd64-1.9.58.zip -d $HOME
   - run:
      name: Run Server Unit Tests.
      command: make test
   - run:
      name: Deploy to GAE.
      command: ./scripts/deploy-ci.sh
