version: 2

references:
  front_container_config: &front_container_config
    docker:
      - image: circleci/node
    working_directory: /home/circleci/project

  node_modules_cache_params: &node_modules_cache_params
    key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

  container_config: &container_config
    docker:
      - image: mercari/appengine-go
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /go/src/github.com/howdy39/study-gae-go-circle-ci

  go_vendoring_cache_params: &go_vendoring_cache_params
    key: go-vendoring-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
    paths:
      - /go/src/github.com/howdy39/study-gae-go-circle-ci/vendor

jobs:
  front_build:
    <<: *front_container_config
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Npm $(npm -v)"
      - run:
          name: Set up to Angular.
          command: npm install --no-save
          working_directory: ./client
      - run:
          name: Run Angular Build.
          command: npm run build
          working_directory: ./client
      - run: mkdir -p attach_workspace
      - run: echo "Trying out workspaces" > attach_workspace/echo-output
      - run: cp -rp client/src attach_workspace/src
      - run: cp -rp client/dist attach_workspace/dist
      - persist_to_workspace:
          root: attach_workspace
          paths:
            - echo-output
            - src
            - dist
      - run: cat attach_workspace/echo-output
      - run: ls -la attach_workspace


  server_build:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: attach_workspace
      - run: |
          if [[ $(cat attach_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
      - run: ls -la attach_workspace/src

workflows:
  version: 2
  build:
    jobs:
      - front_build
      - server_build:
          requires:
            - front_build