runtime: go
api_version: go1.8
handlers:
  - url: /(.*\.(gif|png|jpg|css|js|map|eot|svg|ttf|woff|woff2|ico))$
    static_files: templates/\1
    upload: templates/.*\.(gif|png|jpg|css|js|map|eot|svg|ttf|woff|woff2|ico)$
  - url: /.*
    script: _go_app